language: generic
matrix:
  include:
    - script:
        - xcodebuild -scheme Yams test # -sdk macosx -destination arch=x86_64
        - xcodebuild -scheme Yams test -sdk iphonesimulator -destination "name=iPhone 6s"
        - xcodebuild -scheme Yams test -sdk appletvsimulator -destination "name=Apple TV 1080p"
        - xcodebuild -scheme Yams build -sdk watchsimulator -destination "name=Apple Watch - 38mm"
        - pod lib lint
      env: JOB=Xcode
      os: osx
      osx_image: xcode8.2
    - script:
        - swift test
        - swiftlint
      env: JOB=SPM
      os: osx
      osx_image: xcode8.2
    - script: docker run -v `pwd`:/Yams norionomura/sourcekit:301 bash -c "cd /Yams && swift test"
      env: JOB=Linux
      sudo: required
      services: docker
notifications:
  email: false
