language: generic
matrix:
  include:
    - script:
        - xcodebuild -scheme Yams test
        - pod lib lint
      env: JOB=Xcode
      os: osx
      osx_image: xcode8.1
    - script:
        - swift test
        - swiftlint
        - sleep 5 # SwiftLint completes too quickly
      env: JOB=SPM
      os: osx
      osx_image: xcode8.1
    - script: docker run -v `pwd`:/Yams norionomura/sourcekit:301 bash -c "cd /Yams && swift test"
      env: JOB=Linux
      sudo: required
      services: docker
notifications:
  email: false
